apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafscale.componentName" (dict "root" . "component" "console") }}
  labels:
{{ include "kafscale.labels" . | indent 4 }}
    app.kubernetes.io/component: console
spec:
  type: {{ .Values.console.service.type }}
  ports:
    - name: http
      port: {{ .Values.console.service.port }}
      targetPort: http
      protocol: TCP
  selector:
{{ include "kafscale.componentSelectorLabels" (dict "root" . "component" "console") | indent 4 }}
