{{- if .Values.console.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kafscale.componentName" (dict "root" . "component" "console") }}
  labels:
{{ include "kafscale.labels" . | indent 4 }}
    app.kubernetes.io/component: console
{{- with .Values.console.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.console.ingress.className }}
  ingressClassName: {{ .Values.console.ingress.className }}
{{- end }}
{{- if .Values.console.ingress.tls }}
  tls:
{{ toYaml .Values.console.ingress.tls | indent 4 }}
{{- end }}
  rules:
{{- range .Values.console.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
{{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "kafscale.componentName" (dict "root" $ "component" "console") }}
                port:
                  name: http
{{- end }}
{{- end }}
{{- end }}
