apiVersion: v2
name: kafscale
description: Helm chart for the Kafscale operator and console
home: https://github.com/novatechflow/kafscale
icon: https://raw.githubusercontent.com/novatechflow/kafscale/main/docs/assets/icon.png
type: application
version: 0.1.0
appVersion: "0.1.0"
