{{- if not .Values.config.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iceberg-processor.configMapName" . }}
  labels:
    app.kubernetes.io/name: {{ include "iceberg-processor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}
{{- end }}
