{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "iceberg-processor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "iceberg-processor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "iceberg-processor.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "iceberg-processor.fullname" . }}
{{- end }}
