apiVersion: v1
kind: Service
metadata:
  name: {{ include "iceberg-processor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "iceberg-processor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "iceberg-processor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
